# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Wtyczka_AS_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WtyczkaASDialogBase(object):
    def setupUi(self, WtyczkaASDialogBase):
        WtyczkaASDialogBase.setObjectName("WtyczkaASDialogBase")
        WtyczkaASDialogBase.resize(615, 508)
        self.Policz_roznice_wysokosci = QtWidgets.QPushButton(WtyczkaASDialogBase)
        self.Policz_roznice_wysokosci.setGeometry(QtCore.QRect(420, 90, 161, 81))
        self.Policz_roznice_wysokosci.setObjectName("Policz_roznice_wysokosci")
        self.Policz_pole = QtWidgets.QPushButton(WtyczkaASDialogBase)
        self.Policz_pole.setGeometry(QtCore.QRect(420, 200, 161, 81))
        self.Policz_pole.setObjectName("Policz_pole")
        self.Wyniki = QtWidgets.QLabel(WtyczkaASDialogBase)
        self.Wyniki.setGeometry(QtCore.QRect(70, 80, 271, 211))
        self.Wyniki.setObjectName("Wyniki")

        self.retranslateUi(WtyczkaASDialogBase)
        QtCore.QMetaObject.connectSlotsByName(WtyczkaASDialogBase)

    def retranslateUi(self, WtyczkaASDialogBase):
        _translate = QtCore.QCoreApplication.translate
        WtyczkaASDialogBase.setWindowTitle(_translate("WtyczkaASDialogBase", "Projekt2"))
        self.Policz_roznice_wysokosci.setText(_translate("WtyczkaASDialogBase", "Policz_roznice_wysokosci"))
        self.Policz_pole.setText(_translate("WtyczkaASDialogBase", "Policz_pole"))
        self.Wyniki.setText(_translate("WtyczkaASDialogBase", "TextLabel"))
